policies:
  - name: "task_router"
    url: http://model-server:8000/v2/models/task_router_ensemble/infer
    llms:
      - name: Brainstorming
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Chatbot
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Classification
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Closed QA
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Code Generation
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Extraction
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Open QA
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Other
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Rewrite
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Summarization
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Text Generation
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Unknown
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
  - name: "intent_router"
    url: http://model-router:8000/v2/models/intent_router_ensemble/infer
    llms:
      - name: Brainstorming
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Chatbot
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Classification
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Closed QA
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Code Generation
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Extraction
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Open QA
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Other
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Rewrite
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Summarization
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Text Generation
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
      - name: Unknown
        api_base: https://api.openai.com
        api_key: ""
        model: gpt-4o
