apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-router.fullname" . }}-app-config
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
data:
  config.yaml: |-
    router_controller_url: http://{{ include "llm-router.fullname" . }}-router-controller:{{ .Values.routerController.service.port }}
    openai_api_key: "api-key"
    routing_strategy:
      - manual
      - triton 