{{- if .Values.routerController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-router.fullname" . }}-router-controller
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
    app.kubernetes.io/component: router-controller
spec:
  replicas: {{ .Values.routerController.replicas }}
  {{- if .Values.routerController.strategy }}
  strategy:
    {{- toYaml .Values.routerController.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llm-router.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: router-controller
  template:
    metadata:
      labels:
        {{- include "llm-router.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: router-controller
    spec:
      {{- if .Values.routerController.securityContext.pod }}
      securityContext:
        {{- toYaml .Values.routerController.securityContext.pod | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-router-controller
          image: "{{ .Values.global.imageRegistry }}{{ .Values.routerController.image.repository }}:{{ .Values.routerController.image.tag }}"
          imagePullPolicy: {{ .Values.routerController.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.routerController.service.targetPort }}
              protocol: TCP
          env:
            - name: RUST_LOG
              value: {{ .Values.routerController.config.logLevel | default "info" | quote }}
            - name: CONFIG_PATH
              value: {{ .Values.routerController.config.mountPath }}/config.yaml
            - name: NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.routerController.config.apiKeySecret | default "llm-api-keys" }}
                  key: {{ .Values.routerController.config.apiKeySecretKey | default "nvidia_api_key" }}
{{- if .Values.routerController.env }}
{{- toYaml .Values.routerController.env | nindent 12 }}
{{- end }}
          resources:
            {{- toYaml .Values.routerController.resources | nindent 12 }}
          {{- if .Values.routerController.securityContext.container }}
          securityContext:
            {{- toYaml .Values.routerController.securityContext.container | nindent 12 }}
          {{- end }}
          {{- if .Values.routerController.healthChecks.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.routerController.healthChecks.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.routerController.healthChecks.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.routerController.healthChecks.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.routerController.healthChecks.startupProbe }}
          startupProbe:
            {{- toYaml .Values.routerController.healthChecks.startupProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.routerController.config.mountPath }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
{{- if .Values.routerController.config.existingConfigMap }}
            name: {{ .Values.routerController.config.existingConfigMap }}
{{- else }}
            name: {{ include "llm-router.fullname" . }}-router-controller-config
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.routerController.affinity }}
      affinity:
        {{- toYaml .Values.routerController.affinity | nindent 8 }}
      {{- else if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 