{{- if .Values.routerServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-router.fullname" . }}-router-server
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
    app.kubernetes.io/component: router-server
spec:
  type: {{ .Values.routerServer.service.type }}
  ports:
    {{- range .Values.routerServer.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "llm-router.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: router-server
{{- end }} 