apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-router.fullname" . }}-api-keys
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
type: Opaque
data:
  nvidia_api_key: {{ .Values.apiKeys.nvidia_api_key | b64enc | quote }} 